-- Foreign Keys
ALTER TABLE Nation
  ADD CONSTRAINT fk_nation_region FOREIGN KEY (N_REGIONKEY) REFERENCES Region(R_REGIONKEY);

ALTER TABLE Customer
  ADD CONSTRAINT fk_customer_nation FOREIGN KEY (C_NATIONKEY) REFERENCES Nation(N_NATIONKEY);

ALTER TABLE Supplier
  ADD CONSTRAINT fk_supplier_nation FOREIGN KEY (S_NATIONKEY) REFERENCES Nation(N_NATIONKEY);

ALTER TABLE Nation
  ADD CONSTRAINT fk_partsupp_part FOREIGN KEY (PS_PARTKEY) REFERENCES Part(P_PARTKEY);

ALTER TABLE Partsupp
  ADD CONSTRAINT fk_partsupp_supp FOREIGN KEY (PS_SUPPKEY) REFERENCES Supplier(S_SUPPKEY);

ALTER TABLE Orders
  ADD CONSTRAINT fk_orders_customer FOREIGN KEY (O_CUSTKEY) REFERENCES Customer(C_CUSTKEY);

ALTER TABLE Lineitem
  ADD CONSTRAINT fk_lineitem_order FOREIGN KEY (L_ORDERKEY) REFERENCES Orders(O_ORDERKEY);

ALTER TABLE Lineitem
  ADD CONSTRAINT fk_lineitem_partsupp FOREIGN KEY (L_PARTKEY, L_SUPPKEY) REFERENCES Partsupp(PS_PARTKEY, PS_SUPPKEY);


-- Indexes on Foreign Keys
CREATE INDEX IDX_SUPPLIER_NATION_KEY ON Supplier (S_NATIONKEY);
CREATE INDEX IDX_PARTSUPP_PARTKEY ON Partsupp (PS_PARTKEY);
CREATE INDEX IDX_PARTSUPP_SUPPKEY ON Partsupp (PS_SUPPKEY);
CREATE INDEX IDX_CUSTOMER_NATIONKEY ON Customer (C_NATIONKEY);
CREATE INDEX IDX_ORDERS_CUSTKEY ON Orders (O_CUSTKEY);
CREATE INDEX IDX_LINEITEM_ORDERKEY ON Lineitem (L_ORDERKEY);
CREATE INDEX IDX_LINEITEM_PART_SUPP ON Lineitem (L_PARTKEY, L_SUPPKEY);
CREATE INDEX IDX_NATION_REGIONKEY ON Nation (N_REGIONKEY);

-- Additional Indexes for Performance
CREATE INDEX IDX_LINEITEM_SHIPDATE ON Lineitem (L_SHIPDATE, L_DISCOUNT, L_QUANTITY);
CREATE INDEX IDX_ORDERS_ORDERDATE ON Orders (O_ORDERDATE);