ALTER TABLE Partsupp
  ADD CONSTRAINT partsupp_pkey
     PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);

ALTER TABLE Lineitem
  ADD CONSTRAINT lineitem_pkey
     PRIMARY KEY (L_ORDERKEY, L_LINENUMBER);

