spring.application.name=movie-catalog-service
server.port=8081
management.endpoints.web.exposure.include=hystrix.stream
grpc.client.top10-movies-service.address=static://localhost:500
grpc.client.top10-movies-service.negotiation-type=plaintext

api.key=b0af84324ea41ca39f4311c9156e94e3