apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
spec:
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
        - name: weather-station
          image: weather_station:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"